### ISSUE TITLE
Download ERA5 reanalysis data issue

### ISSUE THREAD

**Issue by Ioannis-Faraslis** [DHI-GRAS/sen-et-snap-sta#15]
I would like to create daily ET on 12 August 2019. On the operator
"Download ECMWF ERA5 reanalysis data" I have chosen the same start -end date: 12 August 2019 but I found that same meteo variable were without values. When I have chosen  star date=11 August, end date =12 August,  I was able to proceed further.
Is my approach correct or I'm doing something wrong?
Thanks

**Comment by radosuav** [comment]
I did a test with the same date and an area somewhere in Europe and the data downloaded correctly (see screenshot below). @Ioannis-Faraslis maybe CDS had a problem at the time you were downloading. Could you try again.

![image](https://user-images.githubusercontent.com/4759850/79695516-945c0880-8277-11ea-9426-8ff4cff8bb82.png)

**Comment by Ioannis-Faraslis** [comment]
Thanks for the replay. 
For me also the data downloaded correctly by the in the next procedure "Prepare ERA5 reanalysis data operator" I get an error message . Also I have tried on different date, 17 August 2019, at the same area (Albathete Spain) but the same (please see the attached image). 
When I used Start date=2019-08-17 end date=2019-08-18 then I was able to proceeded to the next step. 
Thanks!
![prepare_reanalysis](https://user-images.githubusercontent.com/62997735/79696816-a04fc680-8287-11ea-84f9-d564f9d0c9db.jpg)

**Comment by radosuav** [comment]
The error happens in the calculation of Average Daily Solar Irradiance (adsi). For this calculation, hourly solar irradiance values from a 24 hour period are used. The period runs from midnight local time to midnight local time. The ECMWF data has timestamps in the UTC time zone so when dates are requested in the data download step the data from midnight UTC to midnight UTC on the specified dates is downloaded. When there is a mismatch between local midnight and UTC midnight (which happens in most cases) and only one day of ECMWF data is downloaded then this error will happen.

I will improve the error message but my recommendation would be to always have a buffer of one day before and after the period of interest. So in your case, this would mean downloading from data from 11th August to 13th August. This data has low resolution so the download volume is still small even if 3 days are downloaded instead of 1.

**Comment by Ioannis-Faraslis** [comment]
Thanks so much!
