### ISSUE TITLE
Error in download ECMWF-ERA5

### ISSUE THREAD

**Issue by AymanRahman** [DHI-GRAS/sen-et-snap-sta#17]
Dear Sirs
I have the following error in download data as NetCDF
[ecmwf_1.zip](https://github.com/DHI-GRAS/senEtSnapSta/files/4496447/ecmwf_1.zip)
![ECMWF_1](https://user-images.githubusercontent.com/43352074/79635106-9fc80a80-8177-11ea-89cf-294833fb2445.png)

**Comment by radosuav** [comment]
You need to register on Copernicus Climate Data Store first. Have a look at [https://cds.climate.copernicus.eu/api-how-to](https://cds.climate.copernicus.eu/api-how-to) and section 3.3.1.12 of the User Manual (make sure you have version 1.1.0 of the user manual, otherwise download it from the [Sen-ET website](http://esa-sen4et.org/outputs/software/)).

**Comment by AymanRahman** [comment]
I did registration yesterday, but in this interface there is NO place to write my username and password. then where have I to put them?

**Comment by radosuav** [comment]
Please read instructions at [https://cds.climate.copernicus.eu/api-how-to](https://cds.climate.copernicus.eu/api-how-to) and the user manual. There is no username and password but a key file which you need to save in you user home directory.
