### ISSUE TITLE
Unrealistic values and curios pattern in map of daily evapotranspiration

### ISSUE THREAD

**Issue by rasc1974** [DHI-GRAS/sen-et-snap-sta#22]
Hello alltogether, due to Your helpfull support, I could create some maps of ETd for landscapes in the eastern part of Germany with SEN-ET. It´s not simple, but totaly interesting to use! However, when I look at the values of the ETd sometimes it is curios, because they can apear in a range from below 0 (e.g. -7.5 mm to more than 10 mm (e.g. 12.4), which is not realistic (see in the first screen shot). Additionally sometimes a pattern of rectangle tiles is visible in the Output of the 'Sharpen LST' - operator. That pattern also appears in the ETd map (see in the second screeshot). Do You have an idea why this pattern appears? And what might be the reason for the unrealistic ETd values below 0?

![SEN-ET_Example_ETd](https://user-images.githubusercontent.com/62097421/82328202-d9429e80-99df-11ea-842c-d7d83c2114e9.PNG)

![grafik](https://user-images.githubusercontent.com/62097421/82328117-bfa15700-99df-11ea-9724-71cc499ebdc7.png)

**Comment by radosuav** [comment]
How large is the overlap between your S2 and S3 scenes? For the sharpening to work properly it should be at least 50 by 50 S3 pixels (around 50 by 50 km) but the larger the better because it results in a more robust sharpening model. Also, it looks like you set the moving window size to be quite small. You could set it to 20 pixels if the overlap is 50x50 but otherwise keep it at 30.

The tiles should be almost invisible in the sharpened LST if the sharpening model worked correctly. This should also fix your fluxes.

**Comment by rasc1974** [comment]
Ok, thanks!
