### ISSUE TITLE
Problem with downloading Sentinel 3 SLSTR data

### ISSUE THREAD

**Issue by georgeboldeanu** [DHI-GRAS/sen-et-snap-sta#4]
Me again, *sorry*. I have issues also when I try to download Sentinel 3 SLSTR data. This time I don't get any errors just the message that none scenes were found (search date stretches for 3 months and nada). I knew that S3 data were ingested in Pre-Operational Hub till last year but that changed now and it's full in Scihub. I am guessing that the problem might be with the sentinelsat api or I can't figure it right now.Also my OS is Windows 10. (I also attached a picture to be more specific) I
![git](https://user-images.githubusercontent.com/34105846/72527759-2cf67d00-3872-11ea-8a97-f48f9e6c7c75.JPG)

**Comment by j08lue** [comment]
> Me again, _sorry_.

😄 No, please, we are grateful for your reports - and patience. Apparently, this issue slipped past our testing that might not have covered all parameter combinations and cases on Windows.

**Comment by alveniz** [comment]
Sets the orbit of Sentinel 3 coverage

**Comment by alveniz** [comment]
Try Setting the orbit of Sentinel 3 coverage


![IMG-20200120-WA0002](https://user-images.githubusercontent.com/58125725/72745898-cda0b180-3b7e-11ea-9158-1da60e6fa66f.jpg)

**Comment by alveniz** [comment]
https://photos.app.goo.gl/JxdnQwHfjoKGQuLZA

**Comment by radosuav** [comment]
The problem is indeed with the "Limit to Sentinel-2 tiles" parameter. Instead of being ignored when it's not set by the user it is assigned a value of "\_$LIMIT_TILES\_". This leads to no scene being founds since this string is obviously not present in any Sentinel-2 scene name. 

@alveniz I think that you were just lucky that the digits from the orbit number are also present in the Sentinel-2 filename. A quick workaround (if you don't want to limit to tiles) is to put a string in this field which exists in all Sentinel-2 scenes, e.g. "S2" or "MSI". We will fix this error within a week.

**Comment by radosuav** [comment]
@alveniz please change your scihub password - it is visible in the screenshot.

**Comment by panakouris** [comment]
I just fixed this bug and pushed the new bundle. You can either re-install the whole bundle or simply delete the directory `<USEPROFILE>\.snap\auxdata\sen-et-conda-Win64\sen-et-snap-scripts\` and clone [this repository](https://github.com/DHI-GRAS/sen-et-snap-scripts/) into `<USEPROFILE>\.snap\auxdata\sen-et-conda-Win64\` to avoid re-installing all the required packages.
