### ISSUE TITLE
Operator Sharpen LST error size raster

### ISSUE THREAD

**Issue by alveniz** [DHI-GRAS/sen-et-snap-sta#7]
Hi @panakouris, after this issue "[Warp to template operator: error in output image...](https://github.com/DHI-GRAS/senEtSnapSta/issues/1)"
the subsequent operators eg. "Sharpen LST with data minning sharpener" etc... have this error:

```
ValueError: operands could not be broadcast together with shapes (1488,1140) (1140,1488) 
Process exited with value 1
Finished tool execution in 17 seconds
```

thanks

**Comment by radosuav** [comment]
Hi @alveniz this issue should also be fixed now. It was related #1 because in both cases there was a bug in setting the dimensions of files written and read by SNAP. 

The package bundle is not prepared yet but you can test the fix by cloning [this](https://github.com/DHI-GRAS/sen-et-snap-scripts) repository into <USEPROFILE>\.snap\auxdata\sen-et-conda-Win64\. Or you could edit <USEPROFILE>\.snap\auxdata\sen-et-conda-Win64\sen-et-snap-scripts\snappy_utils.py as shown in the [bug fix commit](https://github.com/DHI-GRAS/sen-et-snap-scripts/commit/363b3edb112649c8bbcba9db8cbc7faa4eb6e88c).

Please let us know if this resolves the issue.

**Comment by panakouris** [comment]
The package bundle is also updated now! @alveniz @radosuav

**Comment by alveniz** [comment]
its works.

**Comment by ceci3377** [comment]
Hello, 
I'am starting to use Sen-ET (thank you for its developement by the way) in the frame of my research. I've been trying to run all the steps but I find myself stuck with this same issue although I'am using the scripts coming from the updated bundle. 
My team and I can't really find where it could come from as all the results from the previous steps seemed coherent. 
Have u had any reports of this issue poping up again? 
![image](https://user-images.githubusercontent.com/51880978/110132455-7a61e080-7dcb-11eb-9835-d2f35613a523.png)

**Comment by radosuav** [comment]
Hi, have you tried this:

> Or you could edit .snap\auxdata\sen-et-conda-Win64\sen-et-snap-scripts\snappy_utils.py as shown in the [bug fix commit](https://github.com/DHI-GRAS/sen-et-snap-scripts/commit/363b3edb112649c8bbcba9db8cbc7faa4eb6e88c).

Or does the code already look like after the fix?

**Comment by ceci3377** [comment]
Yes the code is already fixed like mentioned in the bug fix

**Comment by radosuav** [comment]
Then I'm not sure... Are you using SNAP 7 or SNAP 8? The plugin was developed and tested only with SNAP 7. Maybe axis order has changed?

**Comment by ceci3377** [comment]
I was using SNAP 8. I switched to SNAP 7 but the error still pops up.

**Comment by radosuav** [comment]
The only other thing that I can think of is the switch of axis ordering in GDAL (https://gdal.org/tutorials/osr_api_tut.html#crs-and-axis-order) but I am not sure if this is relevant here.

The simplest solution would be to reverse the bug fix commit. The Sen-ET project is finished and we don't have the resources to provide support for the plugin but you could try to get community support on the SNAP forum: https://forum.step.esa.int/c/snap/sen4et/37. If you find the root cause or a permanent solution then also please report it on the forum for other users.
